version: '3.3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "16543:80"
    depends_on:
      - db

  wiremock:
    image: duberton/wiremock:1.0
    ports:
      - "9002:8080"
    volumes:
      - ./mocks/__files:/home/wiremock/__files
      - ./mocks/mappings:/home/wiremock/mappings

  localstack:
    build: ./infrastructure
    ports:
      - "4575:4575"
      - "4566:4566"
      - "${PORT_WEB_UI-8085}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES-sns}
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - PORT_WEB_UI=${PORT_WEB_UI-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=sa-east-1
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
