global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'application'
    metrics_path: '/app/monitoring/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8082']